name: Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
        matrix:
          # Use the LTS Release of Node. (https://nodejs.org/en/)
          node-version: [16.x] 

    runs-on: ubuntu-latest

    steps:
    
    # Backend Workflow
    - uses: actions/checkout@v2
    - name: SSH into LUNA
      uses: appleboy/ssh-action@master
      with:
        host: 45.77.6.116 
        username: root
        key: ${{ secrets.PRIV_KEY }}
        port: 19122
        script: |
          cd Gitfit
          git pull origin master
          git status
          cd backend
          docker-compose up -d --build
